In [39]:
import numpy as np 

In [40]:
U = np.array([6,0,3,6]).reshape(-1,1)
V = np.array([4,2,1]).reshape(-1,1)

In [41]:
U.T.shape

(1, 4)

In [42]:
U.shape

(4, 1)

In [43]:
X = np.dot(U,V.T)

In [44]:
Y = np.array([[5,0,7],
             [0,2,0],
             [4,0,0],
             [0,3,6]])

In [45]:
X

array([[24, 12,  6],
       [ 0,  0,  0],
       [12,  6,  3],
       [24, 12,  6]])

In [46]:
Y


array([[5, 0, 7],
       [0, 2, 0],
       [4, 0, 0],
       [0, 3, 6]])

In [47]:
(Y -X)**2

array([[361, 144,   1],
       [  0,   4,   0],
       [ 64,  36,   9],
       [576,  81,   0]])

In [48]:
sub = np.array([19,1,2,8,9])

In [49]:
sum(sub**2)/2

255.5

In [50]:
(sum(U**2)+sum(V**2))/2

array([51.])

In [51]:
Y = np.array([
    [5, 1, 5, 1, 5, 1, 5],
    [1, 5, 1, 5, 1, 5, 1],
    [5, 5, 5, 5, 5, 5, 5],
    [1, 1, 1, 1, 1, 1, 1],
])

U = np.array([
    [1, 5],
    [5, 1],
    [5, 5],
    [1, 1],
])

In [52]:
U_inv = np.linalg.pinv(U)

In [53]:
U_inv@U

array([[ 1.00000000e+00,  1.38777878e-16],
       [-1.66533454e-16,  1.00000000e+00]])

In [54]:
(U_inv@Y).T

array([[ 1.38777878e-16,  1.00000000e+00],
       [ 1.00000000e+00, -1.66533454e-16],
       [ 1.38777878e-16,  1.00000000e+00],
       [ 1.00000000e+00, -1.66533454e-16],
       [ 1.38777878e-16,  1.00000000e+00],
       [ 1.00000000e+00, -1.66533454e-16],
       [ 1.38777878e-16,  1.00000000e+00]])

In [55]:
V = np.array([[0,1],[1,0],[0,1],[1,0],[0,1],[1,0],[0,1]])

In [56]:
U@V.T

array([[5, 1, 5, 1, 5, 1, 5],
       [1, 5, 1, 5, 1, 5, 1],
       [5, 5, 5, 5, 5, 5, 5],
       [1, 1, 1, 1, 1, 1, 1]])

In [57]:
V.T

array([[0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]])

In [58]:
U = np.array([[ 128.27790923 ,  37.21907314],
     [ -24.10214086 , 132.5681096 ],
     [  86.81314031 , 141.48931895],
     [  17.36262806  , 28.29786379]])

V = np.array([[ 0.03494581 ,-0.00298991,  0.03494581 ,-0.00298991 , 0.03494581 ,-0.00298991, 0.03494581],
              [ 0.01389677,  0.03717287 , 0.01389677,  0.03717287  ,0.01389677,  0.03717287 ,0.01389677]])


In [59]:
U@V

array([[5.00000034, 1.00000036, 5.00000034, 1.00000036, 5.00000034,
        1.00000036, 5.00000034],
       [0.99999969, 5.00000034, 0.99999969, 5.00000034, 0.99999969,
        5.00000034, 0.99999969],
       [5.00000003, 5.00000058, 5.00000003, 5.00000058, 5.00000003,
        5.00000058, 5.00000003],
       [1.00000001, 1.00000012, 1.00000001, 1.00000012, 1.00000001,
        1.00000012, 1.00000001]])

n = number of people  
m = number of movies  
k = rank   
U ; n x k   
V ; m x k  
D if the dataset (a,i) pairs  
Y ; n x m data matrix  

In [60]:
B = np.array([[1,10],[1,10],[10,1],[1,10],[10,1]])
Z = np.array([[1],[1],[5],[1],[5]])

In [61]:
B

array([[ 1, 10],
       [ 1, 10],
       [10,  1],
       [ 1, 10],
       [10,  1]])

In [62]:
Z

array([[1],
       [1],
       [5],
       [1],
       [5]])

In [63]:
import numpy as np

B = np.array([[1,10],
              [1,10],
              [10,1],
              [1,10],
              [10,1]])

Z = np.array([[1],
              [1],
              [5],
              [1],
              [5]])

λ = 1  # You can set this to any regularization strength

# Step 1: Compute B^T B
BtB = B.T @ B

# Step 2: Add λI
lambda_I = λ * np.eye(B.shape[1])
BtB_reg = BtB + lambda_I

# Step 3: Compute B^T Z
BtZ = B.T @ Z

# Step 4: Solve for u(a)
u_a = np.linalg.inv(BtB_reg) @ BtZ

print(u_a)


[[0.49246358]
 [0.05074858]]


In [64]:
u_a.T@np.array([[10],[1]])

array([[4.97538441]])

In [65]:
Y = np.array([
    [4, 3, 1],
    [1, 3, -2],
    [5, 2, 3]
])

# Compute full SVD
U_full, S_full, VT_full = np.linalg.svd(Y)

# Take top-2 components (rank = 2)
U2 = U_full[:, :2]            # 3x2
S2 = np.diag(S_full[:2])      # 2x2
VT2 = VT_full[:2, :]          # 2x3

# Factor as Y = U * V^T, where:
U = U2 @ np.sqrt(S2)          # 3x2
V = VT2.T @ np.sqrt(S2)       # 3x2, so V^T is 2x3

# Final output:
print("U =\n", U)
print("\nV^T =\n", V.T)

U =
 [[-1.7851464  -0.36906234]
 [-0.60386134 -1.72046899]
 [-2.10887487  0.80505251]]

V^T =
 [[-2.28646009 -1.42331912 -0.86314097]
 [ 0.22127969 -1.24414484  1.46542453]]


In [66]:
U@V.T

array([[ 4.,  3.,  1.],
       [ 1.,  3., -2.],
       [ 5.,  2.,  3.]])

In [67]:
def pred(data, x):
    (a, i, r) = data
    (u, b_u, v, b_v) = x
    return np.dot(u[a].T,v[i]) + b_u[a] + b_v[i]
  
# X : n x k
# Y : n
def ridge_analytic(X, Y, lam):
    (n, k) = X.shape
    xm = np.mean(X, axis = 0, keepdims = True)   # 1 x n
    ym = np.mean(Y)                              # 1 x 1
    Z = X - xm                                   # d x n
    T = Y - ym                                   # 1 x n
    th = np.linalg.solve(np.dot(Z.T, Z) + lam * np.identity(k), np.dot(Z.T, T))
    # th_0 account for the centering
    th_0 = (ym - np.dot(xm, th))                 # 1 x 1
    return th.reshape((k,1)), float(th_0)

In [68]:
 def pred(data, x):
    (a, i, r) = data
    (u, b_u, v, b_v) = x
    return np.dot(u[a].T,v[i]) + b_u[a] + b_v[i]
  
# X : n x k
# Y : n
def ridge_analytic(X, Y, lam):
    (n, k) = X.shape
    xm = np.mean(X, axis = 0, keepdims = True)   # 1 x n
    ym = np.mean(Y)                              # 1 x 1
    Z = X - xm                                   # d x n
    T = Y - ym                                   # 1 x n
    th = np.linalg.solve(np.dot(Z.T, Z) + lam * np.identity(k), np.dot(Z.T, T))
    # th_0 account for the centering
    th_0 = (ym - np.dot(xm, th))                 # 1 x 1
    return th.reshape((k,1)), float(th_0)

In [69]:
Z = np.array([[1], [1], [5], [1], [5], [5], [1]])
b_v = np.array([[3], [3], [3], [3], [3], [5], [1]])
B = np.array([[1, 10], [1, 10], [10, 1], [1, 10], [10, 1], [5, 5], [5, 5]])
# Solution with offsets, using ridge_analytic provided in code file
u_a, b_u_a = ridge_analytic(B, (Z - b_v), 1)
u_a, b_u_a

(array([[ 0.22024566],
        [-0.22193986]]),
 0.007623888182962335)

In [70]:
u_a_no_b = np.dot(np.linalg.inv(np.dot(B.T, B) + 1 * np.identity(2)), np.dot(B.T, Z))
u_a_no_b

array([[0.50148126],
       [0.0562376 ]])

In [71]:
np.array([1,10])@u_a_no_b

array([1.0638573])

In [72]:
import pdb
import numpy as np
import time
import pickle

genres = ['Western', 'Comedy', 'Children', 'Crime', 'Musical',
          'Adventure', 'Drama', 'Horror', 'War', 'Documentary',
          'Romance', 'Animation', 'Film-Noir', 'Sci-Fi', 'Mystery',
          'Fantasy', 'IMAX', 'Action', 'Thriller']

# Data is a list of (a, i, r) triples
ratings_small = \
[(0, 0, 5), (0, 1, 3), (0, 3, 1),
 (1, 0, 4), (1, 3, 1),
 (2, 0, 1), (2, 1, 1), (2, 3, 5),
 (3, 0, 1), (3, 3, 4),
 (4, 1, 1), (4, 2, 5), (4, 3, 4)]

def pred(data, x):
    (a, i, r) = data
    (u, b_u, v, b_v) = x
    return np.dot(u[a].T,v[i]) + b_u[a] + b_v[i]

# X : n x k
# Y : n
def ridge_analytic(X, Y, lam):
    (n, k) = X.shape
    xm = np.mean(X, axis = 0, keepdims = True)   # 1 x n
    ym = np.mean(Y)                              # 1 x 1
    Z = X - xm                                   # d x n
    T = Y - ym                                   # 1 x n
    th = np.linalg.solve(np.dot(Z.T, Z) + lam * np.identity(k), np.dot(Z.T, T))
    # th_0 account for the centering
    th_0 = (ym - np.dot(xm, th))                 # 1 x 1
    return th.reshape((k,1)), float(th_0)

# Example from lab handout
Z = np.array([[1], [1], [5], [1], [5], [5], [1]])
b_v = np.array([[3], [3], [3], [3], [3], [5], [1]])
B = np.array([[1, 10], [1, 10], [10, 1], [1, 10], [10, 1], [5, 5], [5, 5]])
# Solution with offsets, using ridge_analytic provided in code file
u_a, b_u_a = ridge_analytic(B, (Z - b_v), 1)
print('With offsets', u_a, b_u_a)
# Solution using previous model, with no offsets
u_a_no_b = np.dot(np.linalg.inv(np.dot(B.T, B) + 1 * np.identity(2)), np.dot(B.T, Z))
print('With no offsets', u_a_no_b)

# After retrieving the output x from mf_als, you can use this function to save the output so
# you don't have to re-train your model
def save_model(x):
    pickle.dump(x, open("ALSmodel", "wb"))

# After training and saving your model once, you can use this function to retrieve the previous model
def load_model():
    x = pickle.load(open("ALSmodel", "rb"))
    return x

# Compute the root mean square error
def rmse(data, x):
    error = 0.
    for datum in data:
        error += (datum[-1] - pred(datum, x))**2
    return np.sqrt(error/len(data))

# Counts of users and movies, used to calibrate lambda
def counts(data, index):
    item_count = {}
    for datum in data:
        j = datum[index]
        if j in item_count:
            item_count[j] += 1
        else:
            item_count[j] = 1
    c = np.ones(max(item_count.keys())+1)
    for i,v in item_count.items(): c[i]=v
    return c

# The ALS outer loop
def mf_als(data_train, data_validate, k=2, lam=0.02, max_iter=100, verbose=False):
    # size of the problem
    n = max(d[0] for d in data_train)+1 # users
    m = max(d[1] for d in data_train)+1 # items
    # which entries are set in each row and column
    us_from_v = [[] for i in range(m)]
    vs_from_u = [[] for a in range(n)]
    for (a, i, r) in data_train:
        us_from_v[i].append((a, r))
        vs_from_u[a].append((i, r))
    # Initial guess at u, b_u, v, b_v
    # Note that u and v are lists of column vectors (columns of U, V).
    x = ([np.random.normal(1/k, size=(k,1)) for a in range(n)],
          np.zeros(n),
          [np.random.normal(1/k, size=(k,1)) for i in range(m)],
          np.zeros(m))
    # Alternation, modifies the contents of x
    start_time = time.time()
    for i in range(max_iter):
        update_U(data_train, vs_from_u, x, k, lam)
        update_V(data_train, us_from_v, x, k, lam)
        if verbose:
            print('train rmse', rmse(data_train, x), 'validate rmse', data_validate and rmse(data_validate, x))
        if data_validate == None: # code is slower, print out progress
            print("Iteration {} finished. Total Elapsed Time: {:.2f}".format(i + 1, time.time() - start_time))
    # The root mean square errors measured on validate set
    if data_validate != None:
        print('ALS result for k =', k, ': rmse train =', rmse(data_train, x), '; rmse validate =', rmse(data_validate, x))
    return x

def update_U(data, vs_from_u, x, k, lam):
    (u, b_u, v, b_v) = x
    # Your code here
    return x

#Test case for update_U
def update_U_test():
  '''
  This is a test function provided to help you debug your implementation
  '''
  k = 2
  lam = 0.01
  
  vs_from_u = \
  [[(0, 5), (1, 3), (3, 1)],
   [(0, 4), (3, 1)],
   [(0, 1), (1, 1), (3, 5)],
   [(0, 1), (3, 4)],
   [(1, 1), (2, 5), (3, 4)]]
  
  np.random.seed(0)
  
  first = []
  for i in range(5):
    first.append(np.random.rand(2, 1))
  second = np.zeros((5, 1))
  third = []
  for i in range(5):
    third.append(np.random.rand(2, 1))
  fourth = np.zeros((5, 1))
  x0 = (first, second, third, fourth)
  
  x_result = update_U(ratings_small, vs_from_u, x0, k, lam)
  
  x_list = [[u.tolist() for u in x_result[0]],
            x_result[1].tolist(),
            [v.tolist() for v in x_result[2]],
            x_result[3].tolist()]
  
  
  assert np.all(np.isclose(x_list[0], np.array([[[4.048442188078757], [-2.5000082235465526]],
                                                [[3.2715388359271054], [-1.2879317400952521]],
                                                [[-6.237522315961142], [-2.9639103597721355]],
                                                [[-3.2715388359271054], [1.2879317400952521]],
                                                [[-4.87111151185168], [-1.761023196019822]] ])))
  assert np.all(np.isclose(x_list[1], 
                           np.array([[3.043665230868208], [2.048616799474877], [7.462166369240114], [2.951383200525123], [5.487071919883842]])))
  assert np.all(np.isclose(x_list[2], np.array([[[0.7917250380826646], [0.5288949197529045]],
                                       [[0.5680445610939323], [0.925596638292661]],
                                       [[0.07103605819788694], [0.08712929970154071]],
                                       [[0.02021839744032572], [0.832619845547938]],
                                       [[0.7781567509498505], [0.8700121482468192]] ])))
  assert np.all(np.isclose(x_list[3], np.array([[0.0], [0.0], [0.0], [0.0], [0.0]])))
  print("Test passed!")
  
#update_U_test()

def update_V(data, us_from_v, x, k, lam):
    (u, b_u, v, b_v) = x
    # Your code here
    return x

# Simple validate case
mf_als(ratings_small, ratings_small,lam=0.01, max_iter=10, k=2)

# The SGD outer loop
def mf_sgd(data_train, data_validate, step_size_fn, k=2, lam=0.02, max_iter=100, verbose=False):
    # size of the problem
    ndata = len(data_train)
    n = max(d[0] for d in data_train)+1
    m = max(d[1] for d in data_train)+1
    # Distribute the lambda among the users and items
    lam_uv = lam/counts(data_train,0), lam/counts(data_train,1)
    # Initial guess at u, b_u, v, b_v (also b)
    x = ([np.random.normal(1/k, size=(k,1)) for j in range(n)],
         np.zeros(n),
         [np.random.normal(1/k, size=(k,1)) for j in range(m)],
         np.zeros(m))
    di = int(max_iter/10.)
    for i in range(max_iter):
        if i%di == 0 and verbose:
            print('i=', i, 'train rmse=', rmse(data_train, x),
                  'validate rmse', data_validate and rmse(data_validate, x))
        step = step_size_fn(i)
        j = np.random.randint(ndata)            # pick data item
        sgd_step(data_train[j], x, lam_uv, step) # modify x
    print('SGD result for k =', k, ': rmse train =', rmse(data_train, x), '; rmse validate =', rmse(data_validate, x))
    return x

def sgd_step(data, x, lam, step):
    (a, i, r) = data
    (u, b_u, v, b_v) = x
    (lam_u, lam_v) = lam
    # Your code here
    return x

def sgd_step_test():
  '''
  This is a test function provided to help you debug your implementation
  '''
  step = 0.025
  lam =(np.array([ 0.00333333,  0.005,  0.00333333,  0.005,  0.00333333]), np.array([ 0.0025,  0.00333333,  0.01,  0.002]))
  
  np.random.seed(0)
  
  first = []
  for i in range(5):
    first.append(np.random.rand(2, 1))
  second = np.zeros((5, 1))
  third = []
  for i in range(5):
    third.append(np.random.rand(2, 1))
  fourth = np.zeros((5, 1))
  x0 = (first, second, third, fourth)
  
  x_result = sgd_step(ratings_small[3], x0, lam, step)
  
  x_list = [[u.tolist() for u in x_result[0]],
            x_result[1].tolist(),
            [v.tolist() for v in x_result[2]],
            x_result[3].tolist()]
    
  assert np.all(np.isclose(x_list[0], np.array([[[0.5488135039273248], [0.7151893663724195]],
                                                [[0.6667107015911342], [0.5875840438721468]],
                                                [[0.4236547993389047], [0.6458941130666561]],
                                                [[0.4375872112626925], [0.8917730007820798]],
                                                [[0.9636627605010293], [0.3834415188257777]]])))
  assert np.all(np.isclose(x_list[1], np.array([[0.0], [0.08086477989447478], [0.0], [0.0], [0.0]])))
  assert np.all(np.isclose(x_list[2], np.array([[[0.8404178830022684], [0.5729237224816648]],
                                                [[0.5680445610939323], [0.925596638292661]],
                                                [[0.07103605819788694], [0.08712929970154071]],
                                                [[0.02021839744032572], [0.832619845547938]],
                                                [[0.7781567509498505], [0.8700121482468192]]])))
  assert np.all(np.isclose(x_list[3], np.array([[0.08086477989447478], [0.0], [0.0], [0.0], [0.0]])))
  print("Test passed!")
  
#sgd_step_test()


# Simple validate case
mf_sgd(ratings_small, ratings_small, step_size_fn=lambda i: 0.1,
       lam=0.01, max_iter=1000, k=2)

def load_ratings_data_small(path_data='ratings.csv'):
    """
    Returns two lists of triples (a, i, r) (training, validate)
    """
    # we want to "randomly" sample but make it deterministic
    def user_hash(uid):
        return 71 * uid % 401
    def user_movie_hash(uid, iid):
        return (17 * uid + 43 * iid) % 61
    data_train = []
    data_validate = []
    with open(path_data) as f_data:
        for line in f_data:
            (uid, iid, rating, timestamp) = line.strip().split(",")
            h1 = user_hash(int(uid))
            if h1 <= 40:
                h2 = user_movie_hash(int(uid), int(iid))
                if h2 <= 12:
                    data_validate.append([int(uid), int(iid), float(rating)])
                else:
                    data_train.append([int(uid), int(iid), float(rating)])
    print('Loading from', path_data,
          'users_train', len(set(x[0] for x in data_train)),
          'items_train', len(set(x[1] for x in data_train)),
          'users_validate', len(set(x[0] for x in data_validate)),
          'items_validate', len(set(x[1] for x in data_validate)))
    return data_train, data_validate

def load_ratings_data(path_data='ratings.csv'):
    """
    Returns a list of triples (a, i, r)
    """
    data = []
    with open(path_data) as f_data:
        for line in f_data:
            (uid, iid, rating, timestamp) = line.strip().split(",")
            data.append([int(uid), int(iid), float(rating)])

    print('Loading from', path_data,
          'users', len(set(x[0] for x in data)),
          'items', len(set(x[1] for x in data)))
    return data

def load_movies(path_movies='movies.csv'):
    """
    Returns a dictionary mapping item_id to item_name and another dictionary
    mapping item_id to a list of genres
    """
    data = {}
    genreMap = {}
    with open(path_movies, encoding = "utf8") as f_data:
        for line in f_data:
            parts = line.strip().split(",")
            item_id = int(parts[0])
            item_name = ",".join(parts[1:-1]) # file is poorly formatted
            item_genres = parts[-1].split("|")
            data[item_id] = item_name
            genreMap[item_id] = item_genres
    return data, genreMap

def baseline(train, validate):
    item_sum = {}
    item_count = {}
    total = 0
    for (i, j, r) in train:
        total += r
        if j in item_sum:
            item_sum[j] += 3
            item_count[j] += 1
        else:
            item_sum[j] = r
            item_count[j] = 1
    error = 0
    avg = total/len(train)
    for (i, j, r) in validate:
        pred = item_sum[j]/item_count[j] if j in item_count else avg
        error += (r - pred)**2
    return np.sqrt(error/len(validate))

# Load the movie data
# Below is code for the smaller dataset, used in section 3 of the HW
def tuning_als(max_iter_als=20, verbose=False):
    b1, v1 = load_ratings_data_small()
    print('Baseline rmse (predict item average)', baseline(b1, v1))
    print('Running on the MovieLens data')
    lams = [0.1,1,10,100]
    ks = [1,2,3]
    for k in ks:
        for lam in lams:
            print('ALS, k =', k, 'and lam', lam)
            mf_als(b1, v1, lam = lam, max_iter=max_iter_als, k=k, verbose=verbose)


With offsets [[ 0.22024566]
 [-0.22193986]] 0.007623888182962335
With no offsets [[0.50148126]
 [0.0562376 ]]
ALS result for k = 2 : rmse train = [[4.04812043]] ; rmse validate = [[4.04812043]]
SGD result for k = 2 : rmse train = [[3.46965976]] ; rmse validate = [[3.46965976]]


In [73]:
def mf_als(data_train, data_validate, k=2, lam=0.02, max_iter=100, verbose=False):
    # size of the problem
    n = max(d[0] for d in data_train)+1 # users
    m = max(d[1] for d in data_train)+1 # items
    # which entries are set in each row and column and the rating
    us_from_v = [[] for i in range(m)]
    vs_from_u = [[] for a in range(n)]
    for (a, i, r) in data_train:
        us_from_v[i].append((a, r))
        vs_from_u[a].append((i, r))
    # Initial guess at u, b_u, v, b_v
    # Note that u and v are lists of column vectors (rows of U, V).
    x = ([np.random.normal(1/k, size=(k,1)) for a in range(n)],
          np.zeros(n),
          [np.random.normal(1/k, size=(k,1)) for i in range(m)],
          np.zeros(m))
    # Alternation, modifies the contents of x
    for i in range(max_iter):
        update_U(data_train, vs_from_u, x, k, lam)
        update_V(data_train, us_from_v, x, k, lam)
    # The root mean square errors measured on validate set
    if data_validate != None:
        print('ALS result for k =', k, ': rmse =', rmse(data_validate, x))
    return x

In [74]:
# This function calls ridge_analytic, which is already defined.
def update_U(data, vs_from_u, x, k, lam):
    (u, b_u, v, b_v) = x
    for a in range(len(u)):
        if not vs_from_u[a]: continue
        V = np.hstack([v[i] for (i, _) in vs_from_u[a]]).T
        y = np.array([r-b_v[i] for (i, r) in vs_from_u[a]])
        u[a], b_u[a] = ridge_analytic(V, y, lam)
    return x
# This is analogous
def update_V(data, us_from_v, x, k, lam):
    (u, b_u, v, b_v) = x
    for i in range(len(v)):
        if not us_from_v[i]: continue
        V = np.hstack([u[a] for (a, _) in us_from_v[i]]).T
        y = np.array([r-b_u[a] for (a, r) in us_from_v[i]])
        v[i], b_v[i] = ridge_analytic(V, y, lam)
    return x

In [75]:
def mf_sgd(data_train, data_validate, step_size_fn, k=2, lam=0.02, max_iter=100, verbose=False):
    # size of the problem
    ndata = len(data_train)
    n = max(d[0] for d in data_train)+1
    m = max(d[1] for d in data_train)+1
    # Distribute the lambda among the users and items
    lam_uv = lam/counts(data_train,0), lam/counts(data_train,1)
    # Initial guess at u, b_u, v, b_v (also b)
    x = ([np.random.normal(1/k, size=(k,1)) for j in range(n)],
         np.zeros(n),
         [np.random.normal(1/k, size=(k,1)) for j in range(m)],
         np.zeros(m))
    di = int(max_iter/10.)
    for i in range(max_iter):
        if i%di == 0 and verbose:
            print('i=', i, 'train rmse=', rmse(data_train, x),
                  'validate rmse', data_validate and rmse(data_validate, x))
        step = step_size_fn(i)
        j = np.random.randint(ndata)            # pick data item
        sgd_step(data_train[j], x, lam_uv, step) # modify x
    print('SGD result for k =', k, ': rmse =', rmse(data_validate, x))
    return x

In [76]:
def sgd_step(data, x, lam, step):
    (a, i, r) = data
    (u, b_u, v, b_v) = x
    (lam_u, lam_v) = lam
    # predicted rating
    pred = np.dot(u[a].T,v[i]) + b_u[a] + b_v[i]
    # prediction error
    e = r - pred
    temp_u = u[a]           # so we don't update v with updated u
    u[a] = u[a] - step*(-e*v[i] + lam_u[a]*u[a])
    b_u[a] = b_u[a] - step*(-e)
    v[i] = v[i] - step*(-e*temp_u + lam_v[i]*v[i])
    b_v[i] = b_v[i] - step*(-e)
    return x

In [77]:
load_ratings_data_small('ratings.csv')

Loading from ratings.csv users_train 1360 items_train 2000 users_validate 1265 items_validate 1986


([[243, 1015, 4.0],
  [243, 2384, 3.0],
  [243, 2942, 4.0],
  [486, 1092, 5.0],
  [486, 2541, 5.0],
  [486, 8533, 5.0],
  [808, 1, 4.0],
  [808, 45, 3.5],
  [808, 186, 4.0],
  [808, 252, 4.0],
  [808, 333, 3.0],
  [808, 440, 4.0],
  [808, 588, 3.5],
  [808, 596, 4.0],
  [808, 628, 3.0],
  [808, 784, 3.5],
  [808, 852, 3.5],
  [808, 953, 5.0],
  [808, 1073, 4.0],
  [808, 1198, 3.0],
  [808, 1242, 4.0],
  [808, 1270, 4.5],
  [808, 1291, 3.0],
  [808, 1917, 3.0],
  [808, 2011, 4.0],
  [808, 2012, 3.5],
  [808, 2080, 4.0],
  [808, 2268, 3.5],
  [808, 2355, 4.0],
  [808, 2804, 2.5],
  [808, 2858, 4.0],
  [808, 3114, 4.0],
  [808, 3408, 4.0],
  [808, 4022, 4.5],
  [808, 4886, 4.5],
  [808, 4896, 5.0],
  [808, 4993, 2.5],
  [808, 5299, 4.0],
  [808, 5377, 5.0],
  [808, 5816, 4.0],
  [808, 6708, 3.0],
  [819, 5, 2.0],
  [819, 107, 2.5],
  [819, 158, 2.0],
  [819, 168, 0.5],
  [819, 376, 0.5],
  [819, 524, 0.5],
  [819, 596, 2.0],
  [819, 616, 3.0],
  [819, 1242, 0.5],
  [819, 1513, 2.0],
  [81

In [78]:
load_ratings_data(path_data='ratings.csv')


Loading from ratings.csv users 13366 items 2000


[[11, 32, 3.5],
 [11, 34, 4.0],
 [11, 47, 3.5],
 [11, 110, 3.5],
 [11, 165, 3.5],
 [11, 231, 2.5],
 [11, 260, 3.0],
 [11, 296, 4.0],
 [11, 318, 4.5],
 [11, 344, 3.0],
 [11, 356, 4.0],
 [11, 364, 3.0],
 [11, 457, 3.5],
 [11, 480, 3.5],
 [11, 500, 4.0],
 [11, 520, 2.0],
 [11, 527, 4.5],
 [11, 593, 4.0],
 [11, 736, 3.0],
 [11, 750, 3.0],
 [11, 784, 2.0],
 [11, 1073, 4.0],
 [11, 1089, 3.5],
 [11, 1127, 3.5],
 [11, 1265, 2.5],
 [11, 1270, 3.0],
 [11, 1276, 3.0],
 [11, 1370, 3.5],
 [11, 1527, 3.5],
 [11, 1573, 3.5],
 [11, 1721, 4.0],
 [11, 1923, 4.0],
 [11, 2028, 4.0],
 [11, 2054, 2.5],
 [11, 2571, 3.0],
 [11, 2959, 2.5],
 [11, 3408, 4.0],
 [11, 3409, 4.0],
 [11, 3513, 3.5],
 [11, 3555, 4.0],
 [11, 3578, 4.0],
 [11, 3977, 3.0],
 [11, 4022, 3.5],
 [11, 4027, 3.5],
 [11, 4226, 2.5],
 [11, 4238, 3.5],
 [11, 4878, 2.0],
 [11, 4963, 3.5],
 [11, 4973, 4.5],
 [11, 4993, 4.0],
 [11, 4995, 4.0],
 [11, 5064, 4.5],
 [11, 5418, 3.5],
 [11, 5952, 4.0],
 [11, 5989, 4.0],
 [11, 6377, 3.5],
 [11, 6539, 2.5]

In [79]:
load_movies(path_movies='movies.csv')

({1: 'Toy Story (1995)',
  2: 'Jumanji (1995)',
  3: 'Grumpier Old Men (1995)',
  4: 'Waiting to Exhale (1995)',
  5: 'Father of the Bride Part II (1995)',
  6: 'Heat (1995)',
  7: 'Sabrina (1995)',
  9: 'Sudden Death (1995)',
  10: 'GoldenEye (1995)',
  11: '"American President, The (1995)"',
  12: 'Dracula: Dead and Loving It (1995)',
  14: 'Nixon (1995)',
  15: 'Cutthroat Island (1995)',
  16: 'Casino (1995)',
  17: 'Sense and Sensibility (1995)',
  18: 'Four Rooms (1995)',
  19: 'Ace Ventura: When Nature Calls (1995)',
  20: 'Money Train (1995)',
  21: 'Get Shorty (1995)',
  22: 'Copycat (1995)',
  23: 'Assassins (1995)',
  24: 'Powder (1995)',
  25: 'Leaving Las Vegas (1995)',
  26: 'Othello (1995)',
  28: 'Persuasion (1995)',
  29: '"City of Lost Children, The (Cité des enfants perdus, La) (1995)"',
  31: 'Dangerous Minds (1995)',
  32: 'Twelve Monkeys (a.k.a. 12 Monkeys) (1995)',
  34: 'Babe (1995)',
  36: 'Dead Man Walking (1995)',
  39: 'Clueless (1995)',
  41: 'Richard III (1

In [81]:
data = load_ratings_data()
movies_dict, genres_dict = load_movies()
model = mf_als(data, None, k=10, lam=1, max_iter=20)
save_model(model)

Loading from ratings.csv users 13366 items 2000


In [82]:
model = load_model()