In [133]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import numpy as np
from sklearn.datasets import load_digits


In [134]:
digits = load_digits()

In [135]:
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'frame': None, 'feature_names': ['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4', 'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1', 'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6', 'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3', 'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0', 'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5', 'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2', 'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7', 'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4', 'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', '

In [136]:
x = digits.data
y = digits.target

In [137]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

In [138]:
print(x_train)

[[ 0.  0. 15. ...  0.  0.  0.]
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  1. 13. ... 16. 12.  0.]
 ...
 [ 0.  0.  2. ...  0.  0.  0.]
 [ 0.  0. 15. ...  3.  0.  0.]
 [ 0.  0.  3. ...  0.  0.  0.]]


In [139]:
print(y_train)

[5 7 2 ... 8 5 1]


In [140]:
model_lr = LogisticRegression()


In [141]:
model_lr.fit(x_train,y_train)
model_lr.score(x_test,y_test)

c:\Anaconda\envs\dul01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [142]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)

0.9944444444444445

In [143]:
from sklearn.ensemble import RandomForestClassifier 
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(x_train,y_train)
rf_classifier.score(x_test,y_test)

0.9694444444444444

In [144]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)


In [145]:
def get_score (model , X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [147]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(x):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

    score_l.append(get_score(model_lr,x_train,x_test,y_train,y_test))
    score_svm.append(get_score(svm,x_train,x_test,y_train,y_test))
    score_rf.append(get_score(rf_classifier,x_train,x_test,y_train,y_test))


c:\Anaconda\envs\dul01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Anaconda\envs\dul01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = 

In [148]:
score_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [149]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [150]:
score_rf

[0.9382303839732888, 0.9565943238731218, 0.9265442404006677]

In [151]:
from sklearn.model_selection import cross_val_score

In [153]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

c:\Anaconda\envs\dul01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Anaconda\envs\dul01\lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = 

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [154]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [158]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91944444, 0.91111111, 0.95264624, 0.96657382, 0.91643454])

In [162]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.91388889, 0.90277778, 0.95821727, 0.96935933, 0.92479109])