In [82]:
import numpy as np  

def perceptron_through_origin(X, y):
    """
    Implements the perceptron algorithm for data through the origin.
    
    Parameters:
    X: numpy array of shape (n_samples, n_features) - Input data
    y: numpy array of shape (n_samples,) - Labels (+1 or -1)
    
    Returns:
    theta: numpy array - Final weight vector
    mistakes: int - Number of mistakes before convergence
    """
    theta = np.zeros(X.shape[1])  # Initialize weight vector to zero
    mistakes = 0
    converged = False

    while not converged:
        converged = True  # Assume convergence unless a mistake is made
        for i in range(len(y)):
            if y[i] * np.dot(theta, X[i]) <= 0:  # Check for misclassification
                theta += y[i] * X[i]  # Update weights
                mistakes += 1
                converged = False  # Not yet converged
    
    return theta, mistakes





In [83]:
X = np.array([[0.2,0.2,0.8,0.8],
              [0.0002,0.0002,0.0008,0.0008],
              [1,1,1,1]])
y = np.array([-1,-1,1,1])

In [84]:
X = np.array([[0.2,0.2,0.8,0.8],
              [0.0002,0.0002,0.0008,0.0008],
              [1,1,1,1]])
y = np.array([-1,-1,1,1])

def perceptron_1(X, y, max_iterations=1000):
    weights = np.zeros(X.shape[1])
    mistakes = 0

    for _ in range(max_iterations):
        global_mistakes = 0
        for i in range(len(y)):
            # Calculate the prediction
            prediction = np.sign(np.dot(X[i], weights))
            # Update weights if prediction is wrong
            if prediction != y[i]:
                weights += y[i] * X[i]
                global_mistakes += 1
        mistakes += global_mistakes
        # Stop if no mistakes are made
        if global_mistakes == 0:
            break

    return mistakes

mistakes = perceptron(X, y)    

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
mistakes

(array([[ 2.8e+00],
        [ 2.8e-03],
        [-1.0e+00]]),
 array([-1.]),
 100)

In [ ]:
import numpy as np

# Data
# X = np.array([[0.2, 0.2, 0.8, 0.8],
#               [0.0002, 0.0002, 0.0008, 0.0008],
#               [1, 1, 1, 1]])
# y = np.array([-1, -1, 1, 1])

X = np.array([[0.2,0.2,0.8,0.8],
              [0.0002,0.0002,0.0008,0.0008],
              [1,1,1,1]])
y = np.array([-1,-1,1,1])

# Perceptron algorithm
def perceptron_1(X, y, max_iterations=1000):
    weights = np.zeros(X.shape[0])  # Adjust to match the number of features
    mistakes = 0

    for _ in range(max_iterations):
        global_mistakes = 0
        for i in range(len(y)):
            # Calculate the prediction
            prediction = np.sign(np.dot(X[:, i], weights))  # Update the dot product computation
            # Update weights if prediction is wrong
            if prediction != y[i]:
                weights += y[i] * X[:, i]
                global_mistakes += 1
        mistakes += global_mistakes
        # Stop if no mistakes are made
        if global_mistakes == 0:
            break

    return (mistakes,weights)

# Run the Perceptron
mistakes = perceptron_1(X, y)
mistakes


(7, array([ 1.6e+00,  1.6e-03, -1.0e+00]))

In [ ]:
def perceptron_2(X, y, max_iterations=1000):
    weights = np.zeros(X.shape[0])  # Adjust to match the number of features
    mistakes = 0

    for _ in range(max_iterations):
        global_mistakes = 0
        for i in range(len(y)):
            # Calculate the prediction
            prediction = np.sign(np.dot(X[i], weights))  # Update the dot product computation
            # Update weights if prediction is wrong
            if prediction != y[i]:
                weights += y[i] * X[i]
                global_mistakes += 1
        mistakes += global_mistakes
        # Stop if no mistakes are made
        if global_mistakes == 0:
            break

    return (mistakes,weights)
data =   np.array([[2, 3,  4,  5],[1,1,1,1]])
labels = np.array([1, 1, -1, -1])
perceptron_1(data,labels)

(29, array([-2.,  7.]))

In [ ]:
def perceptron_3(data, labels, params = {}, hook = None):    
    # if T not in params, default to 100
    T = params.get('T', 100)
    # Your implementation here
    d, n = data.shape
    theta = np.zeros((d,1))
    theta_0 = np.zeros(1)
    print("d = {}, n = {}, theta shape = {}, theta_0 shape = {}".format(d,n,theta.shape,theta_0.shape))
  
    for t in range(T):     
      for i in range(n):
        y = labels[0,i]
        x = data[:,i]
        
        a = np.dot(x,theta)+theta_0
        #print("a = {}".format(a))
        positive = np.sign(y*a)
        
        if np.sign(y*a) <=0: # update the thetas
          theta[:,0] = theta[:,0]+ y*x
          theta_0 = theta_0 + y
          
    print("shape x = {}, y = {}, theta = {}, theta_0 = {}".format(x.shape,y.shape,theta.shape,theta_0.shape))
    return (theta,theta_0)
data =   np.array([[2, 3,  4,  5]])
labels = np.array([[1, 1, -1, -1]])
perceptron_3(data,labels)

d = 1, n = 4, theta shape = (1, 1), theta_0 shape = (1,)
shape x = (1,), y = (), theta = (1, 1), theta_0 = (1,)


(array([[-2.]]), array([7.]))

In [ ]:
import numpy as np

def one_hot(x, k):
    bias = np.zeros((k,1))
    bias[x-1] = 1
    return bias

In [88]:
one_hot(5,7)

array([[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [89]:

data = np.array([[[0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]],[[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]],[[0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.]],
       [[0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]]])
labels = np.array([[1, 1, -1, -1]])  
perceptron_3 (data,labels)

ValueError: too many values to unpack (expected 2)

In [94]:
import numpy as np

def perceptron_hone_hot(X, y, max_iterations=1000):
    """Perceptron algorithm implementation."""
    # Ensure X is a 2D array (samples, features)
    if X.ndim == 3:  
        X = X.reshape(X.shape[0], X.shape[1])  # Convert (samples, features, 1) → (samples, features)
    
    # Ensure y is a 1D array
    y = y.flatten()  # Convert (1, N) → (N,)
    
    # Initialize weights
    weights = np.zeros(X.shape[1])  # Number of features
    mistakes = 0

    for _ in range(max_iterations):
        global_mistakes = 0
        for i in range(len(y)):
            # Compute the prediction
            prediction = np.sign(np.dot(X[i], weights))
            # Update weights if prediction is wrong
            if prediction != y[i]:
                weights += y[i] * X[i]
                global_mistakes += 1
        mistakes += global_mistakes
        # Stop if no mistakes are made
        if global_mistakes == 0:
            break

    return weights

# Fix input shapes
data = np.array([[[0.], [1.], [0.], [0.], [0.], [0.], [1.]],
                 [[0.], [0.], [1.], [0.], [0.], [0.], [1.]],
                 [[0.], [0.], [0.], [1.], [0.], [0.], [1.]],
                 [[0.], [0.], [0.], [0.], [1.], [0.], [1.]]])

labels = np.array([[1, 1, -1, -1]])

# Run perceptron
weights = perceptron_hone_hot(data, labels)
weights


array([ 0.,  2.,  1., -2., -1.,  0.,  0.])

In [95]:
data = np.array([[[1.], [0.], [0.], [0.], [0.], [0.], [1.]],
                 [[0.], [1.], [0.], [0.], [0.], [0.], [1.]],
                 [[0.], [0.], [1.], [0.], [0.], [0.], [1.]],
                 [[0.], [0.], [0.], [1.], [0.], [0.], [1.]],
                 [[0.], [0.], [0.], [0.], [1.], [0.], [1.]],
                 [[0.], [0.], [0.], [0.], [0.], [1.], [1.]]])

labels = np.array([[1,1,-1,-1,1,1]])
weights = perceptron_hone_hot(data, labels)
weights

array([ 1.,  1., -2., -2.,  1.,  1.,  0.])