In [1]:
import numpy as np 

In [7]:
w = np.array([[1, -1, -2], 
              [-1, 2, 1]])

x = np.array([[1, 1]])
y = np.array([[0, 1, 0]])

In [9]:
z = np.dot(x,w)


In [14]:
def softmax(z):
    exp_z = np.exp(z)  
    return exp_z / np.sum(exp_z)

In [16]:
a = softmax(z)

In [21]:
der = np.dot(x.T,a-y)

In [22]:
der

array([[ 0.24472847, -0.33475904,  0.09003057],
       [ 0.24472847, -0.33475904,  0.09003057]])

In [23]:
a

array([[0.24472847, 0.66524096, 0.09003057]])

In [24]:
w_n = w - 0.5*der

In [25]:
w_n

array([[ 0.87763576, -0.83262048, -2.04501529],
       [-1.12236424,  2.16737952,  0.95498471]])

In [26]:
softmax(x@w_n)

array([[0.15918761, 0.77245284, 0.06835955]])

In [6]:
x = np.array([[0.5,0,-3],
             [0.5,2,0.5],
             [1,1,1]])

w = np.array([[1,0,-1,0],
             [0,1,0,-1],
             [-1,-1,-1,-1]])
x.T@w

array([[-0.5, -0.5, -1.5, -1.5],
       [-1. ,  1. , -1. , -3. ],
       [-4. , -0.5,  2. , -1.5]])

In [8]:
w.T@x

array([[-0.5, -1. , -4. ],
       [-0.5,  1. , -0.5],
       [-1.5, -1. ,  2. ],
       [-1.5, -3. , -1.5]])

In [7]:
u = np.array([[0, 0, 0, 0],
       [0 ,  1. , 0 , 0 ],
       [0 , 0,  2. , 0]])
u.T

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.],
       [0., 0., 0.]])

In [6]:
import numpy as np
u = np.random.randint(1,8,(3,4))
u


array([[1, 2, 2, 6],
       [3, 3, 5, 7],
       [3, 6, 3, 3]])

In [7]:
u**2

array([[ 1,  4,  4, 36],
       [ 9,  9, 25, 49],
       [ 9, 36,  9,  9]])

In [8]:
u.T@u

array([[19, 29, 26, 36],
       [29, 49, 37, 51],
       [26, 37, 38, 56],
       [36, 51, 56, 94]])

In [10]:
1 - u**2

array([[  0,  -3,  -3, -35],
       [ -8,  -8, -24, -48],
       [ -8, -35,  -8,  -8]])

In [11]:
x = np.random.randint(-5,5,(4,5))

In [13]:
x

array([[ 2,  1,  0, -4, -3],
       [ 4,  1,  0, -2,  3],
       [-2, -1, -1, -4, -3],
       [-5,  4,  4,  1,  1]])

In [12]:
np.maximum(0,x)

array([[2, 1, 0, 0, 0],
       [4, 1, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 4, 4, 1, 1]])

In [14]:
y = np.random.randint(3,9,(4,5))

In [15]:
y

array([[6, 7, 5, 6, 8],
       [5, 3, 6, 7, 4],
       [5, 4, 5, 3, 5],
       [6, 8, 4, 7, 6]])

In [18]:
y*(np.maximum(0,x)>0)

array([[6, 7, 0, 0, 0],
       [5, 3, 0, 0, 4],
       [0, 0, 0, 0, 0],
       [0, 8, 4, 7, 6]])

In [22]:
u = np.random.randint(1,8,(3,4))
exp = np.exp(u)
exp/np.sum(exp,axis=0)

array([[0.49832117, 0.72973621, 0.00664835, 0.25949646],
       [0.00335766, 0.26845495, 0.00664835, 0.70538451],
       [0.49832117, 0.00180884, 0.98670329, 0.03511903]])

In [23]:
exp

array([[1096.63315843, 1096.63315843,    2.71828183,   20.08553692],
       [   7.3890561 ,  403.42879349,    2.71828183,   54.59815003],
       [1096.63315843,    2.71828183,  403.42879349,    2.71828183]])